"""initial schema

Revision ID: d03e4c8cf034
Revises:
Create Date: 2026-06-17 14:46:10.284178+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d03e4c8cf034"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Esquemas que gestiona el proyecto. Su ciclo de vida vive aquí (versionado y
# reversible), no en env.py.
SCHEMAS = ("meta", "raw", "core", "market", "features", "models", "betting")

# Tablas con columna updated_at que replican el trigger BEFORE UPDATE de schema.sql.
# (esquema, tabla, nombre_trigger)
UPDATED_AT_TRIGGERS = (
    ("meta", "sources", "trg_sources_updated"),
    ("core", "competitions", "trg_competitions_updated"),
    ("core", "venues", "trg_venues_updated"),
    ("core", "teams", "trg_teams_updated"),
    ("core", "players", "trg_players_updated"),
    ("core", "matches", "trg_matches_updated"),
)


def upgrade() -> None:
    """Upgrade schema."""
    # Crear los esquemas ANTES de cualquier tabla.
    for schema in SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("iso_code", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("confederation", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_countries")),
        sa.UniqueConstraint("iso_code", name=op.f("uq_countries_iso_code")),
        schema="core",
    )
    op.create_table(
        "match_statuses",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_terminal", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_match_statuses")),
        schema="core",
    )
    op.create_table(
        "sports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sports")),
        sa.UniqueConstraint("code", name=op.f("uq_sports_code")),
        schema="core",
    )
    op.create_table(
        "feature_sets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_sets")),
        sa.UniqueConstraint("version", name=op.f("uq_feature_sets_version")),
        schema="features",
    )
    op.create_table(
        "bookmakers",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_sharp", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmakers")),
        sa.UniqueConstraint("code", name=op.f("uq_bookmakers_code")),
        schema="market",
    )
    op.create_table(
        "market_types",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("has_line", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_market_types")),
        schema="market",
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('api', 'scraper', 'manual')", name=op.f("ck_sources_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("code", name=op.f("uq_sources_code")),
        schema="meta",
    )
    op.create_table(
        "competitions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("sport_id", sa.UUID(), nullable=False),
        sa.Column("country_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('league', 'cup', 'international', 'friendly')",
            name=op.f("ck_competitions_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["core.countries.id"],
            name=op.f("fk_competitions_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["core.sports.id"],
            name=op.f("fk_competitions_sport_id_sports"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
        sa.UniqueConstraint(
            "sport_id",
            "country_id",
            "name",
            "kind",
            name=op.f("uq_competitions_sport_id_country_id_name_kind"),
        ),
        schema="core",
    )
    op.create_table(
        "players",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("position", sa.Text(), nullable=True),
        sa.Column("country_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["core.countries.id"],
            name=op.f("fk_players_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
        schema="core",
    )
    op.create_table(
        "source_entity_map",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("internal_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('competition', 'season', 'team', 'player', 'venue', 'match')",
            name=op.f("ck_source_entity_map_entity_type"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["meta.sources.id"],
            name=op.f("fk_source_entity_map_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_entity_map")),
        sa.UniqueConstraint(
            "source_id",
            "entity_type",
            "external_id",
            name=op.f("uq_source_entity_map_source_id_entity_type_external_id"),
        ),
        schema="core",
    )
    op.create_index(
        "idx_source_map_internal",
        "source_entity_map",
        ["entity_type", "internal_id"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "venues",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("country_id", sa.UUID(), nullable=True),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column("altitude_m", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["core.countries.id"],
            name=op.f("fk_venues_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venues")),
        schema="core",
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("flow_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'running'"), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("rows_written", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed', 'partial')",
            name=op.f("ck_ingestion_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["meta.sources.id"],
            name=op.f("fk_ingestion_runs_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
        schema="meta",
    )
    op.create_index(
        "idx_ingestion_runs_source",
        "ingestion_runs",
        ["source_id", sa.literal_column("started_at DESC")],
        unique=False,
        schema="meta",
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("algorithm", sa.Text(), nullable=False),
        sa.Column(
            "hyperparameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("feature_set_id", sa.UUID(), nullable=True),
        sa.Column("train_data_from", sa.Date(), nullable=True),
        sa.Column("train_data_to", sa.Date(), nullable=True),
        sa.Column("code_hash", sa.Text(), nullable=True),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feature_set_id"],
            ["features.feature_sets.id"],
            name=op.f("fk_model_versions_feature_set_id_feature_sets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("name", "version", name=op.f("uq_model_versions_name_version")),
        schema="models",
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("competition_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["core.competitions.id"],
            name=op.f("fk_seasons_competition_id_competitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint(
            "competition_id", "label", name=op.f("uq_seasons_competition_id_label")
        ),
        schema="core",
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("sport_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("country_id", sa.UUID(), nullable=True),
        sa.Column("home_venue_id", sa.UUID(), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["core.countries.id"],
            name=op.f("fk_teams_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["home_venue_id"],
            ["core.venues.id"],
            name=op.f("fk_teams_home_venue_id_venues"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["core.sports.id"],
            name=op.f("fk_teams_sport_id_sports"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        schema="core",
    )
    op.create_table(
        "data_quality_checks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column("check_name", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), server_default=sa.text("'warning'"), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'error', 'critical')",
            name=op.f("ck_data_quality_checks_severity"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["meta.ingestion_runs.id"],
            name=op.f("fk_data_quality_checks_ingestion_run_id_ingestion_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_checks")),
        schema="meta",
    )
    op.create_index(
        "idx_dq_checks_run",
        "data_quality_checks",
        ["ingestion_run_id"],
        unique=False,
        schema="meta",
    )
    op.create_table(
        "payloads",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["meta.ingestion_runs.id"],
            name=op.f("fk_payloads_ingestion_run_id_ingestion_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["meta.sources.id"],
            name=op.f("fk_payloads_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payloads")),
        schema="raw",
    )
    op.create_index(
        "idx_raw_payloads_hash", "payloads", ["request_hash"], unique=False, schema="raw"
    )
    op.create_index(
        "idx_raw_payloads_source",
        "payloads",
        ["source_id", sa.literal_column("fetched_at DESC")],
        unique=False,
        schema="raw",
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("home_team_id", sa.UUID(), nullable=False),
        sa.Column("away_team_id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=True),
        sa.Column("status_code", sa.Text(), nullable=False),
        sa.Column("round", sa.Text(), nullable=True),
        sa.Column("kickoff_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kickoff_tz", sa.Text(), nullable=True),
        sa.Column("home_goals", sa.SmallInteger(), nullable=True),
        sa.Column("away_goals", sa.SmallInteger(), nullable=True),
        sa.Column("home_goals_ht", sa.SmallInteger(), nullable=True),
        sa.Column("away_goals_ht", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("home_team_id <> away_team_id", name=op.f("ck_matches_distinct_teams")),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["core.teams.id"],
            name=op.f("fk_matches_away_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["core.teams.id"],
            name=op.f("fk_matches_home_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["core.seasons.id"],
            name=op.f("fk_matches_season_id_seasons"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["status_code"],
            ["core.match_statuses.code"],
            name=op.f("fk_matches_status_code_match_statuses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["core.venues.id"],
            name=op.f("fk_matches_venue_id_venues"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
        schema="core",
    )
    op.create_index("idx_matches_away", "matches", ["away_team_id"], unique=False, schema="core")
    op.create_index("idx_matches_home", "matches", ["home_team_id"], unique=False, schema="core")
    op.create_index("idx_matches_kickoff", "matches", ["kickoff_utc"], unique=False, schema="core")
    op.create_index("idx_matches_season", "matches", ["season_id"], unique=False, schema="core")
    op.create_table(
        "player_team",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["core.players.id"],
            name=op.f("fk_player_team_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["core.teams.id"],
            name=op.f("fk_player_team_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_team")),
        sa.UniqueConstraint(
            "player_id",
            "team_id",
            "from_date",
            name=op.f("uq_player_team_player_id_team_id_from_date"),
        ),
        schema="core",
    )
    op.create_table(
        "team_aliases",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["meta.sources.id"],
            name=op.f("fk_team_aliases_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["core.teams.id"],
            name=op.f("fk_team_aliases_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_aliases")),
        sa.UniqueConstraint("alias", "source_id", name=op.f("uq_team_aliases_alias_source_id")),
        schema="core",
    )
    op.create_table(
        "team_season",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["core.seasons.id"],
            name=op.f("fk_team_season_season_id_seasons"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["core.teams.id"],
            name=op.f("fk_team_season_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_season")),
        sa.UniqueConstraint("team_id", "season_id", name=op.f("uq_team_season_team_id_season_id")),
        schema="core",
    )
    op.create_table(
        "match_team_stats",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("xg", sa.Double(), nullable=True),
        sa.Column("xga", sa.Double(), nullable=True),
        sa.Column("possession", sa.Double(), nullable=True),
        sa.Column("shots", sa.SmallInteger(), nullable=True),
        sa.Column("shots_on_tgt", sa.SmallInteger(), nullable=True),
        sa.Column("corners", sa.SmallInteger(), nullable=True),
        sa.Column("fouls", sa.SmallInteger(), nullable=True),
        sa.Column("yellow_cards", sa.SmallInteger(), nullable=True),
        sa.Column("red_cards", sa.SmallInteger(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["core.matches.id"],
            name=op.f("fk_match_team_stats_match_id_matches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["meta.sources.id"],
            name=op.f("fk_match_team_stats_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["core.teams.id"],
            name=op.f("fk_match_team_stats_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_team_stats")),
        sa.UniqueConstraint(
            "match_id", "team_id", name=op.f("uq_match_team_stats_match_id_team_id")
        ),
        schema="core",
    )
    op.create_index(
        "idx_match_team_stats_team", "match_team_stats", ["team_id"], unique=False, schema="core"
    )
    op.create_table(
        "match_team_features",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("feature_set_id", sa.UUID(), nullable=False),
        sa.Column("as_of_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feature_set_id"],
            ["features.feature_sets.id"],
            name=op.f("fk_match_team_features_feature_set_id_feature_sets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["core.matches.id"],
            name=op.f("fk_match_team_features_match_id_matches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["core.teams.id"],
            name=op.f("fk_match_team_features_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_team_features")),
        sa.UniqueConstraint(
            "match_id",
            "team_id",
            "feature_set_id",
            "as_of_timestamp",
            name=op.f("uq_match_team_features_match_id_team_id_feature_set_id_as_of_timestamp"),
        ),
        schema="features",
    )
    op.create_index(
        "idx_features_match",
        "match_team_features",
        ["match_id", "feature_set_id"],
        unique=False,
        schema="features",
    )
    op.create_table(
        "odds_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("bookmaker_id", sa.UUID(), nullable=False),
        sa.Column("market_type", sa.Text(), nullable=False),
        sa.Column("selection_code", sa.Text(), nullable=False),
        sa.Column("line", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("decimal_odds", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload_id", sa.UUID(), nullable=True),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decimal_odds > 1.0", name=op.f("ck_odds_snapshots_decimal_odds_gt_one")
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["market.bookmakers.id"],
            name=op.f("fk_odds_snapshots_bookmaker_id_bookmakers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["meta.ingestion_runs.id"],
            name=op.f("fk_odds_snapshots_ingestion_run_id_ingestion_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["market_type"],
            ["market.market_types.code"],
            name=op.f("fk_odds_snapshots_market_type_market_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["core.matches.id"],
            name=op.f("fk_odds_snapshots_match_id_matches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["raw.payloads.id"],
            name=op.f("fk_odds_snapshots_raw_payload_id_payloads"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odds_snapshots")),
        sa.UniqueConstraint(
            "match_id",
            "bookmaker_id",
            "market_type",
            "selection_code",
            "line",
            "recorded_at",
            name=op.f(
                "uq_odds_snapshots_match_id_bookmaker_id_market_type_selection_code_line_recorded_at"
            ),
        ),
        schema="market",
    )
    op.create_index(
        "idx_odds_match_mkt",
        "odds_snapshots",
        ["match_id", "market_type", "selection_code"],
        unique=False,
        schema="market",
    )
    op.create_index(
        "idx_odds_match_time",
        "odds_snapshots",
        ["match_id", sa.literal_column("recorded_at DESC")],
        unique=False,
        schema="market",
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("market_type", sa.Text(), nullable=False),
        sa.Column("selection_code", sa.Text(), nullable=False),
        sa.Column("line", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("predicted_prob", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("feature_row_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "predicted_prob BETWEEN 0 AND 1", name=op.f("ck_predictions_predicted_prob_range")
        ),
        sa.ForeignKeyConstraint(
            ["feature_row_id"],
            ["features.match_team_features.id"],
            name=op.f("fk_predictions_feature_row_id_match_team_features"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["market_type"],
            ["market.market_types.code"],
            name=op.f("fk_predictions_market_type_market_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["core.matches.id"],
            name=op.f("fk_predictions_match_id_matches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["models.model_versions.id"],
            name=op.f("fk_predictions_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
        sa.UniqueConstraint(
            "match_id",
            "model_version_id",
            "market_type",
            "selection_code",
            "line",
            name=op.f("uq_predictions_match_id_model_version_id_market_type_selection_code_line"),
        ),
        schema="models",
    )
    op.create_index(
        "idx_predictions_match",
        "predictions",
        ["match_id", "model_version_id"],
        unique=False,
        schema="models",
    )
    op.create_table(
        "value_signals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("prediction_id", sa.UUID(), nullable=False),
        sa.Column("bookmaker_id", sa.UUID(), nullable=False),
        sa.Column("odds_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("model_prob", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("market_implied_prob", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("edge", sa.Numeric(precision=7, scale=5), nullable=False),
        sa.Column("expected_value", sa.Numeric(precision=8, scale=5), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["market.bookmakers.id"],
            name=op.f("fk_value_signals_bookmaker_id_bookmakers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["odds_snapshot_id"],
            ["market.odds_snapshots.id"],
            name=op.f("fk_value_signals_odds_snapshot_id_odds_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["models.predictions.id"],
            name=op.f("fk_value_signals_prediction_id_predictions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_value_signals")),
        schema="betting",
    )
    op.create_index(
        "idx_value_signals_pred", "value_signals", ["prediction_id"], unique=False, schema="betting"
    )
    op.create_table(
        "paper_bets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("value_signal_id", sa.UUID(), nullable=False),
        sa.Column("stake", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("kelly_fraction", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("decimal_odds_taken", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("closing_decimal_odds", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("pnl", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "placed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'won', 'lost', 'void', 'pushed', 'half_won', 'half_lost')",
            name=op.f("ck_paper_bets_status"),
        ),
        sa.CheckConstraint("stake > 0", name=op.f("ck_paper_bets_stake_positive")),
        sa.ForeignKeyConstraint(
            ["value_signal_id"],
            ["betting.value_signals.id"],
            name=op.f("fk_paper_bets_value_signal_id_value_signals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_bets")),
        schema="betting",
    )
    op.create_index(
        "idx_paper_bets_status", "paper_bets", ["status"], unique=False, schema="betting"
    )
    op.create_table(
        "bankroll_ledger",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("entry_type", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paper_bet_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entry_type IN ('deposit', 'withdrawal', 'bet_stake', 'bet_return', 'adjustment')",
            name=op.f("ck_bankroll_ledger_entry_type"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_bet_id"],
            ["betting.paper_bets.id"],
            name=op.f("fk_bankroll_ledger_paper_bet_id_paper_bets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bankroll_ledger")),
        schema="betting",
    )
    op.create_index(
        "idx_ledger_time", "bankroll_ledger", ["occurred_at"], unique=False, schema="betting"
    )
    # ### end Alembic commands ###

    # --- Función y triggers de updated_at (equivalente a schema.sql §0.1) ---
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for schema, table, trigger in UPDATED_AT_TRIGGERS:
        op.execute(
            f"CREATE TRIGGER {trigger} BEFORE UPDATE ON {schema}.{table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )

    # --- Seeds de lookups (idénticos a schema.sql) ---
    op.execute(
        """
        INSERT INTO core.match_statuses (code, description, is_terminal) VALUES
            ('scheduled', 'Programado',                 FALSE),
            ('live',      'En juego',                   FALSE),
            ('finished',  'Finalizado (90 min)',        TRUE),
            ('aet',       'Finalizado tras prórroga',   TRUE),
            ('penalties', 'Definido por penales',       TRUE),
            ('postponed', 'Aplazado',                   FALSE),
            ('abandoned', 'Abandonado',                 TRUE),
            ('awarded',   'Resultado otorgado',         TRUE),
            ('cancelled', 'Cancelado',                  TRUE);
        """
    )
    op.execute(
        """
        INSERT INTO market.market_types (code, name, has_line) VALUES
            ('1x2',  'Resultado 1X2',          FALSE),
            ('ou',   'Más/Menos goles',        TRUE),
            ('ah',   'Hándicap asiático',      TRUE),
            ('btts', 'Ambos equipos marcan',   FALSE);
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ledger_time", table_name="bankroll_ledger", schema="betting")
    op.drop_table("bankroll_ledger", schema="betting")
    op.drop_index("idx_paper_bets_status", table_name="paper_bets", schema="betting")
    op.drop_table("paper_bets", schema="betting")
    op.drop_index("idx_value_signals_pred", table_name="value_signals", schema="betting")
    op.drop_table("value_signals", schema="betting")
    op.drop_index("idx_predictions_match", table_name="predictions", schema="models")
    op.drop_table("predictions", schema="models")
    op.drop_index("idx_odds_match_time", table_name="odds_snapshots", schema="market")
    op.drop_index("idx_odds_match_mkt", table_name="odds_snapshots", schema="market")
    op.drop_table("odds_snapshots", schema="market")
    op.drop_index("idx_features_match", table_name="match_team_features", schema="features")
    op.drop_table("match_team_features", schema="features")
    op.drop_index("idx_match_team_stats_team", table_name="match_team_stats", schema="core")
    op.drop_table("match_team_stats", schema="core")
    op.drop_table("team_season", schema="core")
    op.drop_table("team_aliases", schema="core")
    op.drop_table("player_team", schema="core")
    op.drop_index("idx_matches_season", table_name="matches", schema="core")
    op.drop_index("idx_matches_kickoff", table_name="matches", schema="core")
    op.drop_index("idx_matches_home", table_name="matches", schema="core")
    op.drop_index("idx_matches_away", table_name="matches", schema="core")
    op.drop_table("matches", schema="core")
    op.drop_index("idx_raw_payloads_source", table_name="payloads", schema="raw")
    op.drop_index("idx_raw_payloads_hash", table_name="payloads", schema="raw")
    op.drop_table("payloads", schema="raw")
    op.drop_index("idx_dq_checks_run", table_name="data_quality_checks", schema="meta")
    op.drop_table("data_quality_checks", schema="meta")
    op.drop_table("teams", schema="core")
    op.drop_table("seasons", schema="core")
    op.drop_table("model_versions", schema="models")
    op.drop_index("idx_ingestion_runs_source", table_name="ingestion_runs", schema="meta")
    op.drop_table("ingestion_runs", schema="meta")
    op.drop_table("venues", schema="core")
    op.drop_index("idx_source_map_internal", table_name="source_entity_map", schema="core")
    op.drop_table("source_entity_map", schema="core")
    op.drop_table("players", schema="core")
    op.drop_table("competitions", schema="core")
    op.drop_table("sources", schema="meta")
    op.drop_table("market_types", schema="market")
    op.drop_table("bookmakers", schema="market")
    op.drop_table("feature_sets", schema="features")
    op.drop_table("sports", schema="core")
    op.drop_table("match_statuses", schema="core")
    op.drop_table("countries", schema="core")
    # ### end Alembic commands ###

    # La función ya no tiene triggers que dependan de ella (cayeron con las tablas).
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # Eliminar los esquemas al final: deja la base completamente limpia.
    for schema in SCHEMAS:
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
